# Generated by Django 5.2.17 on 2026-10-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='match_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
